export const SET_BACKDROP = 'SET_BACKDROP';
export const HIDE_BACKDROP = 'HIDE_BACKDROP';

export const GET_POSITION = 'GET_POSITION';

export const FETCH_DIRS_START = 'FETCH_DIRS_START';
export const FETCH_DIRS_SUCCESS = 'FETCH_DIRS_SUCCESS';
export const FETCH_DIRS_FAIL = 'FETCH_DIRS_FAIL';

export const FETCH_FILES_START = 'FETCH_FILES_START';
export const FETCH_FILES_SUCCESS = 'FETCH_FILES_SUCCESS';
export const FETCH_FILES_FAIL = 'FETCH_FILES_FAIL';