export const SET_BACKDROP = 'SET_BACKDROP';
export const HIDE_BACKDROP = 'HIDE_BACKDROP';

export const GET_POSITION = 'GET_POSITION';

export const FETCH_ITEMS_START = 'FETCH_ITEMS_START';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAIL = 'FETCH_ITEMS_FAIL';