export const SET_BACKDROP = 'SET_BACKDROP';
export const HIDE_BACKDROP = 'HIDE_BACKDROP';

export const SET_CONTEXTMENU = 'SET_CONTEXTMENU';
export const HIDE_CONTEXTMENU = 'HIDE_CONTEXTMENU';

export const SET_INFOCARD = 'SET_INFOCARD';
export const HIDE_INFOCARD = 'HIDE_INFOCARD';

export const SET_NEW_DIR = 'SET_NEW_DIR';
export const HIDE_NEW_DIR = 'HIDE_NEW_DIR';

export const SET_FILES_UPLOAD = 'SET_FILES_UPLOAD';

export const SET_RENAME_DIR = 'SET_RENAME_DIR';
export const SET_RENAME_FILE = 'SET_RENAME_FILE';

export const GET_POSITION = 'GET_POSITION';

export const FETCH_DIRS_START = 'FETCH_DIRS_START';
export const FETCH_DIRS_SUCCESS = 'FETCH_DIRS_SUCCESS';
export const FETCH_DIRS_FAIL = 'FETCH_DIRS_FAIL';

export const FETCH_FILES_START = 'FETCH_FILES_START';
export const FETCH_FILES_SUCCESS = 'FETCH_FILES_SUCCESS';
export const FETCH_FILES_FAIL = 'FETCH_FILES_FAIL';

export const BUILD_STRUCTURE = 'BUILD_STRUCTURE';
export const PREPARE_STRUCTURE = 'PREPARE_STRUCTURE';

export const ADD_DIR_TO_PATH = 'ADD_DIR_TO_PATH';
export const OPEN_FROM_PATH = 'OPEN_FROM_PATH';

export const SELECT_DIR = 'SELECT_DIR';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const ADD_SESSION_MESSAGE = 'ADD_SESSION_MESSAGE';
export const REMOVE_SESSION_MESSAGE = 'REMOVE_SESSION_MESSAGE';

export const SET_SHOULD_REDIRECT = 'SET_SHOULD_REDIRECT';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_USER_DATA = 'SET_USER_DATA';

export const SET_SIGNIN_HIGLIGHT = 'SET_SIGNIN_HIGLIGHT';
