# Generated by Django 2.2.4 on 2019-09-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190905_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dir',
            name='dirs',
            field=models.ManyToManyField(blank=True, to='main.Dir'),
        ),
        migrations.AlterField(
            model_name='dir',
            name='files',
            field=models.ManyToManyField(blank=True, to='main.File'),
        ),
    ]
