# Generated by Django 2.2.4 on 2019-09-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190905_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='extension',
            new_name='ext',
        ),
    ]
