# Generated by Django 2.2.4 on 2019-09-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190911_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mmtype',
            field=models.CharField(default='content/file', max_length=100),
        ),
    ]
