# Generated by Django 2.2.4 on 2019-09-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_file_mmtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dir',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
