# Generated by Django 2.2.4 on 2019-09-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190927_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_downloads', models.BigIntegerField(default=0)),
                ('file_uploads', models.BigIntegerField(default=0)),
            ],
        ),
    ]
